/**
 * tailwind-styled-v4 — withTailwindStyled v3
 *
 * Next.js plugin dengan full v3 integration:
 *  - Plugin system
 *  - DevTools overlay
 *  - Static variant compilation
 *  - Dead style elimination
 *  - Route CSS bundling
 *  - React Compiler compat
 *  - Idempotency guard
 */

import fs from "node:fs"
import path from "node:path"
import type { TwPlugin } from "@tailwind-styled/plugin"
import type { NextConfig } from "next"

export interface TailwindStyledNextOptions {
  mode?: "zero-runtime" | "runtime"
  addDataAttr?: boolean
  scanDirs?: string[]
  safelistOutput?: string
  autoClientBoundary?: boolean
  hoist?: boolean
  routeCss?: boolean
  routeCssDir?: string
  atomic?: boolean
  zeroConfig?: boolean
  /** v3: plugins array */
  plugins?: TwPlugin[]
  /** v3: DevTools overlay. Default: true in dev */
  devtools?: boolean
  /** v3: pre-compile all variant combos. Default: true in prod */
  staticVariants?: boolean
  /** v3: remove unused variant CSS at build. Default: true in prod */
  deadStyleElimination?: boolean
  /** v4: incremental CSS compiler — only recompile changed files. Default: true */
  incremental?: boolean
  /** v4: style bucket system — deterministic CSS ordering. Default: true */
  styleBuckets?: boolean
  /** v4: verbose logging untuk incremental engine. Default: false */
  incrementalVerbose?: boolean
}

const LOADER_PATH = require.resolve("./turbopackLoader")
const WEBPACK_LOADER_PATH = require.resolve("./webpackLoader")

export function withTailwindStyled(opts: TailwindStyledNextOptions = {}) {
  return (nextConfig: NextConfig = {}): NextConfig => {
    const cwd = process.cwd()
    const isDev = process.env.NODE_ENV !== "production"

    const hasReactCompiler =
      (nextConfig as any).reactCompiler === true ||
      (nextConfig as any).experimental?.reactCompiler === true

    if (hasReactCompiler && isDev) {
      console.log("[tailwind-styled-v4] React Compiler detected → hoist disabled")
    }

    const {
      scanDirs = ["src"],
      safelistOutput = "src/app/__tw-safelist.css",
      autoClientBoundary = true,
      hoist = !hasReactCompiler,
      atomic = false,
      routeCssDir = path.join(cwd, ".next", "static", "css", "tw"),
      zeroConfig = true,
      plugins = [],
      devtools = isDev,
      staticVariants = !isDev,
      deadStyleElimination = !isDev,
    } = opts

    const routeCss = opts.routeCss !== undefined ? opts.routeCss : !isDev

    if (zeroConfig) {
      try {
        const { bootstrapZeroConfig } = require("@tailwind-styled/compiler")
        bootstrapZeroConfig(cwd)
      } catch {
        /* non-critical */
      }
    }

    // Ensure safelist CSS exists (even empty) so @import in globals.css doesn't fail
    // on first run before generateBuildId has been called.
    const safelistAbsPath = path.isAbsolute(safelistOutput)
      ? safelistOutput
      : path.resolve(cwd, safelistOutput)
    if (!fs.existsSync(safelistAbsPath)) {
      try {
        fs.mkdirSync(path.dirname(safelistAbsPath), { recursive: true })
        fs.writeFileSync(
          safelistAbsPath,
          "/* Auto-generated by tailwind-styled-v4 — DO NOT EDIT */\n"
        )
      } catch {
        /* non-critical */
      }
    }

    if (plugins.length > 0) {
      try {
        const { use } = require("@tailwind-styled/plugin")
        for (const plugin of plugins) use(plugin)
        console.log(
          `[tailwind-styled-v4] ${plugins.length} plugin(s): ${plugins.map((p: TwPlugin) => p.name).join(", ")}`
        )
      } catch (e) {
        console.warn("[tailwind-styled-v4] Plugin init failed:", e)
      }
    }

    const loaderOpts = {
      mode: opts.mode,
      addDataAttr: opts.addDataAttr ?? isDev,
      autoClientBoundary,
      hoist,
      atomic,
      routeCss,
      staticVariants,
    }

    return {
      ...nextConfig,

      experimental: {
        ...(nextConfig.experimental as any),
      },

      // Next.js 16+: turbopack moved to top-level
      // FIX TURBOPACK: pattern "*.{tsx,ts,jsx,js}" terlalu lebar — ikut match
      // node_modules/next/dist/client/*.js.tsx dan trigger "Missing module type".
      // Solusi: scope pattern ke scanDirs saja, jangan catch-all.
      // `as` field dihapus — tidak perlu karena loader output tetap TSX-compatible.
      turbopack: {
        ...(nextConfig as any).turbopack,
        rules: {
          ...Object.fromEntries(
            scanDirs.flatMap((dir: string) => [
              [
                `{./${dir},./src,./app,./pages,./components}/**/*.tsx`,
                {
                  loaders: [{ loader: LOADER_PATH, options: loaderOpts }],
                },
              ],
              [
                `{./${dir},./src,./app,./pages,./components}/**/*.ts`,
                {
                  loaders: [{ loader: LOADER_PATH, options: loaderOpts }],
                },
              ],
            ])
          ),
          ...(nextConfig as any).turbopack?.rules,
        },
      },

      webpack(webpackConfig: any, webpackOpts: any) {
        // FIX #08: idempotency
        const alreadyRegistered = webpackConfig.module.rules.some(
          (r: any) => r._tailwindStyledMarker === true
        )
        if (!alreadyRegistered) {
          webpackConfig.module.rules.push({
            _tailwindStyledMarker: true,
            test: /\.(tsx|ts|jsx|js)$/,
            exclude: /node_modules/,
            use: [
              {
                loader: WEBPACK_LOADER_PATH,
                options: {
                  ...loaderOpts,
                  mode: opts.mode ?? (webpackOpts.dev ? "runtime" : "zero-runtime"),
                  addDataAttr: opts.addDataAttr ?? webpackOpts.dev,
                },
              },
            ],
          })
        }

        if (devtools && webpackOpts.dev) {
          webpackConfig.resolve = webpackConfig.resolve ?? {}
          webpackConfig.resolve.alias = {
            ...(webpackConfig.resolve.alias ?? {}),
            "tailwind-styled-v4/devtools": path.resolve(__dirname, "../../devtools/src/index.tsx"),
          }
        }

        return typeof nextConfig.webpack === "function"
          ? nextConfig.webpack(webpackConfig, webpackOpts)
          : webpackConfig
      },

      generateBuildId: async () => {
        // 1. Safelist — Tailwind v4: output @source inline() CSS (not JSON)
        try {
          const { generateSafelistCss } = require("@tailwind-styled/compiler")
          generateSafelistCss(
            scanDirs.map((d: string) => path.resolve(cwd, d)),
            path.isAbsolute(safelistOutput) ? safelistOutput : path.resolve(cwd, safelistOutput)
          )
          console.log("[tailwind-styled-v4] ✓ Safelist CSS generated")
        } catch (e) {
          console.warn("[tailwind-styled-v4] Safelist skipped:", e)
        }

        // 2. Plugin build hooks
        if (plugins.length > 0) {
          try {
            const { getGlobalRegistry, runBuildHooks } = require("@tailwind-styled/plugin")
            await runBuildHooks(getGlobalRegistry())
            console.log("[tailwind-styled-v4] ✓ Plugin build hooks complete")
          } catch (e) {
            console.warn("[tailwind-styled-v4] Plugin build hooks failed:", e)
          }
        }

        // 3. Route CSS + dead style elimination
        if (routeCss) {
          try {
            const {
              generateAllRouteCss,
              getCollectorSummary,
              runElimination,
            } = require("@tailwind-styled/compiler")

            const results = await generateAllRouteCss({ cwd, outputDir: routeCssDir, minify: true })
            console.log(getCollectorSummary())

            if (deadStyleElimination) {
              let totalSaved = 0
              for (const result of results) {
                const routeFile = path.join(
                  routeCssDir,
                  result.route === "/" ? "index.css" : `${result.route.replace(/\//g, "_")}.css`
                )
                if (fs.existsSync(routeFile)) {
                  const inputCss = fs.readFileSync(routeFile, "utf-8")
                  const { css, report } = runElimination({ dirs: scanDirs, cwd, inputCss })
                  fs.writeFileSync(routeFile, css)
                  totalSaved += report.bytesSaved
                }
              }
              if (totalSaved > 0) {
                console.log(
                  `[tailwind-styled-v4] ✓ Dead styles eliminated: ~${(totalSaved / 1024).toFixed(1)}KB saved`
                )
              }
            }

            const totalKb = results.reduce((s: number, r: any) => s + r.sizeBytes, 0) / 1024
            console.log(
              `[tailwind-styled-v4] ✓ Route CSS: ${results.length} routes, ${totalKb.toFixed(1)}KB`
            )
          } catch (e) {
            console.warn("[tailwind-styled-v4] Route CSS skipped:", e)
          }
        }

        // 4. Plugin CSS
        if (plugins.length > 0) {
          try {
            const {
              getGlobalRegistry,
              generateTokenCss,
              generateUtilityCss,
              applyCssHooks,
            } = require("@tailwind-styled/plugin")
            const registry = getGlobalRegistry()
            let pluginCss = [generateTokenCss(registry), generateUtilityCss(registry)]
              .filter(Boolean)
              .join("\n\n")
            pluginCss = applyCssHooks(pluginCss, registry)
            if (pluginCss.trim()) {
              const outPath = path.join(cwd, "public", "__tw-plugins.css")
              fs.mkdirSync(path.dirname(outPath), { recursive: true })
              fs.writeFileSync(outPath, pluginCss)
              console.log("[tailwind-styled-v4] ✓ Plugin CSS → public/__tw-plugins.css")
            }
          } catch (e) {
            console.warn("[tailwind-styled-v4] Plugin CSS skipped:", e)
          }
        }

        // 5. Incremental engine + bucket system flush
        const { incremental = true, styleBuckets = true, incrementalVerbose = false } = opts
        if (incremental) {
          try {
            const { getIncrementalEngine, getBucketEngine } = require("@tailwind-styled/compiler")

            const engine = getIncrementalEngine({ verbose: incrementalVerbose })
            engine.buildEndSync()

            const stats = engine.getStats()
            console.log(
              `[tailwind-styled-v4] ✓ Incremental: ${stats.changedFiles}/${stats.totalFiles} files changed | ` +
                `+${stats.addedRules} -${stats.removedRules} rules | ${stats.buildTimeMs}ms`
            )

            if (styleBuckets) {
              const buckets = getBucketEngine()
              const allNodes = engine.getAllNodes()
              for (const node of allNodes) buckets.add(node)
              const css = buckets.emit()
              const outPath = path.join(cwd, "public", "__tw-atomic.css")
              fs.mkdirSync(path.dirname(outPath), { recursive: true })
              fs.writeFileSync(outPath, css)
              const bStats = buckets.stats()
              console.log(
                `[tailwind-styled-v4] ✓ Bucket CSS → public/__tw-atomic.css | ` +
                  `${bStats.totalNodes} rules`
              )
            }
          } catch (e) {
            console.warn("[tailwind-styled-v4] Incremental engine flush skipped:", e)
          }
        }

        if (typeof nextConfig.generateBuildId === "function") return nextConfig.generateBuildId()
        return null
      },
    }
  }
}

export default withTailwindStyled
